### ISSUE TITLE
Data via mobile network

### ISSUE THREAD

**Issue by suhasbhairav** [MaJerle/stm32fxxx_hal_libraries#14]
Is it possible to transfer data using GSM2 click module on a discovery board using the HAL libraries? I was not able to find any library associated with GSM/GPRS to do the same.

**Comment by MaJerle** [comment]
it is possible.
You need USART library to interface your GSM module.

I don't have similar library like my esp8266at.com but I'm planning to make similar like that for SIM800 or SIM900 devices.

**Comment by suhasbhairav** [comment]
So does the USART library work for GSM 800/900 ?

**Comment by MaJerle** [comment]
I don't know what knowledge you have in microcontrollers or similar, but:

1. USART is only for communication. Sending/Receiving data.
2. You have to know by yourself what you will send and what you wanna receive back.
