### ISSUE TITLE
ADC Library exceeding maximum code size

### ISSUE THREAD

**Issue by anirudt** [MaJerle/stm32fxxx_hal_libraries#2]
Loading project number 29 onto Keil uVision 5, followed by compiling and linking yields the following error message. 

```
.\Targets\STM32F7_DISCOVERY\project.axf: error: L6050U: The code size of this image (38088 bytes) exceeds the maximum allowed for this version of the linker.
Finished: 0 information, 0 warning, 0 error and 1 fatal error messages.
".\Targets\STM32F7_DISCOVERY\project.axf" - 1 Error(s), 0 Warning(s).
```

A similar issue is found with the DAC library pack. Is there any trivial fix for the above issues with the free software version of Keil uVision?

**Comment by MaJerle** [comment]
Remove unused files from build or buy license.
31. okt. 2015 11:44 dop. je oseba "Anirud Thyagharajan" <
notifications@github.com> napisala:

**Comment by anirudt** [comment]
Could you be a little more specific about "unused" files, pertaining to the application? I ran the DAC application, freshly cloned from the repo. Also, I observed that it was getting compiled for STM32F4** targets. Could you check it for STM32F7?
