### ISSUE TITLE
TM_RTC_Config

### ISSUE THREAD

**Issue by qermit** [MaJerle/stm32fxxx_hal_libraries#5]
TM_RTC_Config does not set all RCC_PeriphCLKInitTypeDef struct entries.
PeriphClockSelection may have random value and HAL_RCCEx_PeriphCLKConfig will hang.

**Comment by MaJerle** [comment]
Let me know about yourfix. According to the clock you wanna init, these
options are used and other ignored.

Waiting your fix.
Have a nice day.
26. nov. 2015 10:36 dop. je oseba "Piotr Miedzik" <notifications@github.com>
napisala:

**Comment by qermit** [comment]
I've created pull request #6 
I'm not sure if this is correct (works with stm32f429l-discovery).

**Comment by qermit** [comment]
> Edit: I have check your "bug" post. As you can see from HAL_RCCEx_PeriphCLKConfig function, it first check for which clock TYPE it goes. If RTCCLK is selected, then it does not use any other types of structure, only these.

**HAL_RCCEx_PeriphCLKConfig** is correct, however nothing is selected in **TM_RTC_Config** and **RCC_PeriphCLKInitTypeDef.PeriphClockSelection** has some garbage that was previously in this memory area. So in my case (24-STM32Fxxx_RTC_LCD) **RCC_PeriphCLKInitTypeDef.PeriphClockSelection** was equal to 1


![tm_rtc](https://cloud.githubusercontent.com/assets/458401/11425292/2e6e55de-9454-11e5-8b5f-14a06abcea30.PNG)

**Comment by MaJerle** [comment]
Yes, true that. I've fixed it, just must upload code.

Thanks for that.
26. nov. 2015 3:42 pop. je oseba "Piotr Miedzik" <notifications@github.com>
napisala:
