### ISSUE TITLE
Source Code for ESP8266 tm_stm32_esp8266_gcc.a

### ISSUE THREAD

**Issue by kangasp** [MaJerle/stm32fxxx_hal_libraries#7]
Will you make the source code available for the tm_stm32_stm32_esp8266_gcc.a ?
Shouldn't that C file be in here too, and not just the archive?
Thanks.

**Comment by MaJerle** [comment]
Please follow my website for more information.

For now, it is not available, but I'm preparing a library which will have source available and will be independent of platform.
